type source_loc = Lexing.position * Lexing.position

val show_source_loc : source_loc -> string

type 'a located = {
  data: 'a;
  source_loc : source_loc;
}

(* Given some data and a source location, wrap them up in the located type. *)
val locate : ?source_loc:source_loc -> 'a -> 'a located 

(* Update the data in a located type using a function f which takes as input the
   old data and outputs the new one.*)
val update_data : 'a located -> ('a -> 'b) -> 'b located

(* Set the data in a located object to new_data *)
val set_data : 'a located -> 'b -> 'b located

(* Pretty printing stuff generated by ppx_deriving.show *)
val pp_located : (Format.formatter -> 'a -> unit) -> Format.formatter -> 'a located -> unit

val data : 'a located -> 'a